/*
 * Copyright (C) 2026 Synapxnet. All rights reserved.
 * This file is Synapxnet Proprietary and Confidential. It is strictly
 * forbidden to copy, distribute, or use without explicit authorization.
 * 消息内命令和回执行为测试 / Inline command and receipt disclosure behavior tests.
 * Author: maoyo | Department: 研发部 | Date: 2026-09-14
 * Version: 1.0.0 | Security Level: INTERNAL
 * __version__: 1.0.0 | __author__: maoyo | __copyright__: Copyright 2026 Synapxnet
 * __maintainer__: maoyo | __email__: synapxnet@gmail.com
 */
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { createRequire } = require('node:module');
const { pathToFileURL } = require('node:url');
const uiRequire = createRequire(path.resolve(__dirname, '../frontend/chat-vite/package.json'));
const vue = uiRequire('vue');
const { parse, compileScript } = uiRequire('@vue/compiler-sfc');
require('../static/js/openxnet-conversation-model.js');
let componentPromise;

/** 编译真实活动组件，避免复制生产逻辑。 / Compile the actual activity component without mirroring production logic. */
async function loadComponent() {
  if (!componentPromise) {
    const filename = path.resolve(__dirname, '../frontend/chat-vite/src/ChatActivity.vue');
    const { descriptor, errors } = parse(fs.readFileSync(filename, 'utf8'), { filename });
    assert.deepEqual(errors, []);
    const vueUrl = pathToFileURL(path.resolve(path.dirname(uiRequire.resolve('vue/package.json')), 'index.mjs')).href;
    const code = compileScript(descriptor, { id: 'chat-activity-disclosure-test', inlineTemplate: true }).content
      .replace(/from ["']vue["']/g, `from '${vueUrl}'`)
      .replace(/import ['"]\.\.\/\.\.\/\.\.\/static\/js\/openxnet-conversation-model\.js['"];?/g, '');
    componentPromise = import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
  }
  return (await componentPromise).default;
}

/** 创建仅记录节点与事件的隔离渲染宿主。 / Create an isolated renderer host that records nodes and events only. */
function createHost() {
  /** 保存真实组件生成的节点。 / Retain nodes generated by the actual component. */
  function node(type, text = '') { return { type, text, props: {}, children: [], parent: null }; }
  const renderer = vue.createRenderer({
    /** 插入或移动节点。 / Insert or move nodes. */
    insert(child, parent, anchor = null) {
      if (child.parent) child.parent.children = child.parent.children.filter((item) => item !== child);
      child.parent = parent;
      const index = anchor ? parent.children.indexOf(anchor) : -1;
      if (index < 0) parent.children.push(child); else parent.children.splice(index, 0, child);
    },
    /** 移除节点。 / Remove nodes. */
    remove(child) { if (child.parent) child.parent.children = child.parent.children.filter((item) => item !== child); },
    /** 建立元素。 / Create elements. */
    createElement: (tag) => node(tag),
    /** 建立文本。 / Create text. */
    createText: (text) => node('#text', text),
    /** 建立注释。 / Create comments. */
    createComment: (text) => node('#comment', text),
    /** 更新文本内容。 / Update text content. */
    setText: (target, text) => { target.text = text; },
    /** 更新元素文本。 / Update element text. */
    setElementText: (target, text) => { target.text = text; target.children = []; },
    /** 获取父节点。 / Get the parent node. */
    parentNode: (target) => target.parent,
    /** 获取相邻节点。 / Get the next sibling. */
    nextSibling: (target) => target.parent?.children[target.parent.children.indexOf(target) + 1] || null,
    /** 保存属性与实际事件处理器。 / Retain attributes and actual event handlers. */
    patchProp: (target, key, previous, next) => { target.props[key] = next; },
  });
  return { renderer, root: node('root') };
}

/** 遍历真实渲染树以定位可操作控件。 / Traverse the actual render tree to find usable controls. */
function nodes(root, predicate) {
  return [...(predicate(root) ? [root] : []), ...root.children.flatMap((child) => nodes(child, predicate))];
}

/** 查找完整类名，避免误匹配相似控件。 / Find complete class names without matching similar controls. */
function byClass(root, className) {
  return nodes(root, (node) => String(node.props.class || '').split(/\s+/).includes(className));
}

/** 读取用户可见文本，忽略注释。 / Read user-visible text while excluding comments. */
function textOf(root) {
  return (root.type === '#comment' ? '' : root.text) + root.children.map(textOf).join('');
}

/** 挂载真实组件并自动清理。 / Mount the actual component and clean it up automatically. */
async function mount(t, steps, options = {}) {
  const { renderer, root } = createHost();
  const component = await loadComponent();
  const inspections = [];
  const state = vue.reactive({ activity: { steps, active: options.active !== false }, isZh: options.isZh !== false });
  const app = renderer.createApp({
    /** 保持可更新 props 以验证消息切换。 / Keep props reactive for message-switch verification. */
    render() { return vue.h(component, { ...state, onInspect: (selection) => inspections.push(selection) }); },
  });
  app.mount(root);
  t.after(() => app.unmount());
  return { root, state, inspections };
}

/** 通过主步骤按钮展开内联记录。 / Expand an inline record through its primary step button. */
async function expand(root, index = 0) {
  byClass(root, 'oxc-worklog__step')[index].props.onClick();
  await vue.nextTick();
}

/** 查找实际展示的输入或回执分段。 / Find an actual displayed input or receipt section. */
function section(root, key) {
  return nodes(root, (node) => node.props['data-section'] === key)[0];
}

/** 使用内存剪贴板替身，禁止修改系统剪贴板。 / Use an in-memory clipboard double without modifying the system clipboard. */
function mockClipboard(t, writeText) {
  const descriptor = Object.getOwnPropertyDescriptor(globalThis, 'navigator');
  Object.defineProperty(globalThis, 'navigator', { configurable: true, value: { clipboard: { writeText } } });
  /** 恢复测试前的全局对象。 / Restore the previous global object after the test. */
  t.after(() => { if (descriptor) Object.defineProperty(globalThis, 'navigator', descriptor); else delete globalThis.navigator; });
}

/** 智能体名称打开协作详情，工具按钮保持内联展开。 / Agent names open collaboration details while tool buttons retain inline expansion. */
test('subagents have distinct glyphs and names open their inspector while tools expand inline', async (t) => {
  const { root, inspections } = await mount(t, [
    { id: 'agent', kind: 'subagent', agentId: 'worker-7', taskId: 'task-3', title: 'Read evidence', status: 'done', output: 'Read-only evidence' },
    { id: 'tool', kind: 'tool', title: 'Inspect input', status: 'pending', input: { record: 'example' } },
  ]);
  assert.equal(byClass(root, 'oxc-worklog__disclosure').length, 0);
  assert.equal(byClass(root, 'oxc-worklog__step')[0].props['aria-expanded'], undefined);
  assert.equal(byClass(root, 'oxc-agent-glyph').length, 1);
  await expand(root);
  assert.equal(byClass(root, 'oxc-worklog__disclosure').length, 0);
  assert.deepEqual(inspections, [{ kind: 'activity', stepId: 'agent' }]);
  assert.match(textOf(root), /子智能体/);
  byClass(root, 'oxc-worklog__inspect')[0].props.onClick();
  assert.equal(inspections.length, 2);
  await expand(root, 1);
  assert.equal(byClass(root, 'oxc-worklog__disclosure').length, 1);
  assert.match(textOf(root), /example/);
  await expand(root, 1);
  assert.equal(byClass(root, 'oxc-worklog__disclosure').length, 0);
});

/** 明确命令字段可以展示，其余参数不可丢失。 / Explicit command fields render while all other arguments remain available. */
test('structured command fields render without discarding input options', async (t) => {
  for (const key of ['cmd', 'command']) {
    const input = { [key]: 'python --version', cwd: 'E:\\review workspace', timeout: 0 };
    const { root } = await mount(t, [{ id: key, title: 'Inspect runtime', status: 'done', input, output: 'Python 3.12' }]);
    await expand(root);
    assert.equal(byClass(section(root, 'command'), 'oxc-worklog__record')[0].text, 'python --version');
    assert.equal(byClass(section(root, 'input'), 'oxc-worklog__record')[0].text, JSON.stringify({ cwd: 'E:\\review workspace', timeout: 0 }, null, 2));
    assert.equal(input[key], 'python --version');
    assert.equal(byClass(section(root, 'output'), 'oxc-worklog__record')[0].text, 'Python 3.12');
  }
  const { root } = await mount(t, [{ id: 'top', command: ['python', '--version'], input: { timeout: 1 }, status: 'done' }]);
  await expand(root);
  assert.equal(byClass(section(root, 'command'), 'oxc-worklog__record')[0].text, '[\n  "python",\n  "--version"\n]');
  assert.match(textOf(section(root, 'input')), /timeout/);
});

/** 普通工具输入不能仅凭标题或文字升级成 shell 命令。 / Ordinary tool input must not become a shell command based on its title or text. */
test('ordinary tool arguments and shell-looking input remain arguments', async (t) => {
  const { root } = await mount(t, [{ id: 'ordinary', title: 'exec_command', kind: 'tool', input: 'echo this is a recorded argument', output: false }]);
  await expand(root);
  assert.equal(section(root, 'command'), undefined);
  assert.equal(byClass(section(root, 'input'), 'oxc-worklog__record')[0].text, 'echo this is a recorded argument');
  assert.equal(byClass(section(root, 'output'), 'oxc-worklog__record')[0].text, 'false');
});

/** 缺失输出和未知状态不会被展示成成功。 / Missing output and unknown status never appear as success. */
test('missing output stays unavailable and does not infer completion', async (t) => {
  const { root } = await mount(t, [{ id: 'unknown', title: 'Waiting for receipt', input: { query: 'sample' } }]);
  await expand(root);
  assert.match(textOf(root), /状态未知/);
  assert.match(textOf(section(root, 'output')), /暂无输出回执/);
  assert.equal(byClass(section(root, 'output'), 'oxc-worklog__copy-action').length, 0);
  assert.doesNotMatch(textOf(root), /已完成/);
});

/** 明确空输出、零和 false 与无回执有不同表现。 / Explicit empty output, zero and false differ from missing receipts. */
test('explicit empty output, zero and false remain real recorded values', async (t) => {
  for (const output of ['', 0, false]) {
    const { root } = await mount(t, [{ id: `value-${String(output)}`, status: 'done', output }]);
    await expand(root);
    const record = section(root, 'output');
    assert.equal(byClass(record, 'oxc-worklog__copy-action').length, 1);
    assert.doesNotMatch(textOf(record), /暂无输出回执/);
    if (output === '') assert.match(textOf(record), /输出为空/);
    else assert.equal(byClass(record, 'oxc-worklog__record')[0].text, String(output));
  }
});

/** 错误与返回 HTML 保持惰性文本且不触发操作。 / Errors and returned HTML stay inert text and trigger no operations. */
test('failed output and executable-looking payloads stay inert and readable', async (t) => {
  const input = '<img src=x onerror=evil()>';
  const output = '<script>evil()</script>';
  const error = 'Command failed: <iframe src="bad"></iframe>';
  const { root, inspections } = await mount(t, [{ id: 'failed', status: 'error', input: { cmd: input }, output, error }]);
  await expand(root);
  assert.match(textOf(byClass(root, 'oxc-worklog__status')[0]), /失败/);
  assert.equal(byClass(section(root, 'command'), 'oxc-worklog__record')[0].text, input);
  assert.equal(byClass(section(root, 'output'), 'oxc-worklog__record')[0].text, output);
  assert.equal(byClass(section(root, 'error'), 'oxc-worklog__record')[0].text, error);
  assert.equal(nodes(root, (node) => ['script', 'img', 'iframe'].includes(node.type) || node.props.innerHTML !== undefined).length, 0);
  assert.deepEqual(inspections, []);
});

/** 复制真实内容与空输出都提供反馈且不修改运行状态。 / Copying real content or empty output reports feedback without changing runtime status. */
test('copy buttons write exact recorded text and report success', async (t) => {
  const copied = [];
  mockClipboard(t, async (text) => { copied.push(text); });
  const { root } = await mount(t, [{ id: 'copy', status: 'done', input: { cmd: 'printf "$VALUE"\nnext command' }, output: '' }]);
  await expand(root);
  for (const key of ['command', 'output']) {
    await byClass(section(root, key), 'oxc-worklog__copy-action')[0].props.onClick();
    await vue.nextTick();
    assert.match(textOf(section(root, key)), /已复制到剪贴板/);
  }
  assert.deepEqual(copied, ['printf "$VALUE"\nnext command', '']);
  assert.match(textOf(byClass(root, 'oxc-worklog__status')[0]), /已完成/);
});

/** 剪贴板失败可见，不能冒充复制完成。 / Clipboard failure stays visible without claiming a successful copy. */
test('clipboard rejection is visible while recorded failure status remains intact', async (t) => {
  mockClipboard(t, async () => { throw new Error('Clipboard denied'); });
  const { root } = await mount(t, [{ id: 'copy-failed', status: 'error', output: 'partial', error: 'Original tool error' }], { isZh: false });
  await expand(root);
  await byClass(section(root, 'output'), 'oxc-worklog__copy-action')[0].props.onClick();
  await vue.nextTick();
  assert.match(textOf(section(root, 'output')), /Copy failed; select the text to copy it/);
  assert.doesNotMatch(textOf(root), /Copied to clipboard/);
  assert.match(textOf(byClass(root, 'oxc-worklog__status')[0]), /Failed/);
  assert.match(textOf(section(root, 'error')), /Original tool error/);
});

/** 流式新增内容不能沿用旧内容的复制成功提示。 / Streamed content must not inherit a successful copy notice for earlier text. */
test('updated output retains its disclosure but clears an outdated copy notice', async (t) => {
  const copied = [];
  mockClipboard(t, async (text) => { copied.push(text); });
  const { root, state } = await mount(t, [{ id: 'stream', status: 'running', output: 'First chunk' }]);
  await expand(root);
  await byClass(section(root, 'output'), 'oxc-worklog__copy-action')[0].props.onClick();
  await vue.nextTick();
  assert.match(textOf(section(root, 'output')), /已复制到剪贴板/);
  state.activity.steps[0].output = 'First chunk\nSecond chunk';
  await vue.nextTick();
  assert.equal(byClass(root, 'oxc-worklog__disclosure').length, 1);
  assert.equal(byClass(section(root, 'output'), 'oxc-worklog__record')[0].text, 'First chunk\nSecond chunk');
  assert.doesNotMatch(textOf(section(root, 'output')), /已复制到剪贴板/);
  assert.deepEqual(copied, ['First chunk']);
});

/** 消息切换清理局部展开并丢弃迟到的复制结果。 / Switching messages clears disclosure and discards late clipboard results. */
test('changing activity clears inline state and ignores stale clipboard completion', async (t) => {
  let resolveCopy;
  mockClipboard(t, () => new Promise((resolve) => { resolveCopy = resolve; }));
  const { root, state } = await mount(t, [{ id: 'old', status: 'done', output: 'Old receipt' }]);
  await expand(root);
  const pending = byClass(section(root, 'output'), 'oxc-worklog__copy-action')[0].props.onClick();
  await vue.nextTick();
  assert.equal(byClass(section(root, 'output'), 'oxc-worklog__copy-action')[0].props.disabled, true);
  state.activity = { active: true, steps: [{ id: 'new', status: 'pending', output: 'New receipt' }] };
  await vue.nextTick();
  assert.equal(byClass(root, 'oxc-worklog__disclosure').length, 0);
  resolveCopy();
  await pending;
  await expand(root);
  assert.match(textOf(section(root, 'output')), /New receipt/);
  assert.doesNotMatch(textOf(root), /Old receipt|已复制|复制中/);
});

/** 回复结束收起一次，历史记录可重新展开且后续回执不抢回用户选择。 / Fold once at reply completion and preserve manual reopening across later receipts. */
test('reply completion collapses activity and file details once while preserving reopening', async (t) => {
  const { root, state } = await mount(t, [{ id: 'edit', status: 'running', fileChanges: [{ id: 'f', path: 'src/a.py', operation: 'modify', status: 'running', diff: '-old\n+new', contentSource: 'request' }] }]);
  await expand(root);
  byClass(root, 'oxc-worklog__file-toggle')[0].props.onClick();
  await vue.nextTick();
  assert.equal(byClass(root, 'oxc-worklog__file-detail').length, 1);
  state.activity.active = false;
  await vue.nextTick();
  assert.equal(byClass(root, 'oxc-worklog__body').length, 0);
  assert.match(textOf(root), /1 个文件/);
  byClass(root, 'oxc-worklog__toggle')[0].props.onClick();
  await vue.nextTick();
  assert.equal(byClass(root, 'oxc-worklog__disclosure').length, 0);
  assert.equal(byClass(root, 'oxc-worklog__file-detail').length, 0);
  state.activity.steps[0].status = 'done';
  await vue.nextTick();
  assert.equal(byClass(root, 'oxc-worklog__body').length, 1);
});

/** 历史结束记录默认折叠，错误与待审批仍可见。 / Completed history starts collapsed while failures and approvals remain visible. */
test('history defaults to a compact summary with failure and approval notices', async (t) => {
  const { root } = await mount(t, [{ id: 'a', status: 'error' }, { id: 'b', status: 'awaiting_approval' }], { active: false });
  assert.equal(byClass(root, 'oxc-worklog__step').length, 0);
  assert.match(textOf(root), /1 项失败/);
  assert.match(textOf(root), /1 项待确认/);
  byClass(root, 'oxc-worklog__toggle')[0].props.onClick();
  await vue.nextTick();
  assert.equal(byClass(root, 'oxc-worklog__step').length, 2);
});

/** 实际文件操作逐项展示，路径打开侧栏，箭头只展开差异。 / Show each file operation, opening paths in the side panel and expanding diffs independently. */
test('file rows expose operation counts and independent diff versus preview actions', async (t) => {
  const files = [
    { id: 'create', path: 'src/new.py', operation: 'create', confirmed: true, status: 'done', additions: 2, deletions: 0, diff: '@@ -0,0 +1,2 @@\n+hello\n+world', contentSource: 'receipt' },
    { id: 'modify', path: 'src/existing.py', operation: 'modify', confirmed: false, status: 'awaiting_approval', before: 'before', after: 'after', additions: null, deletions: null, contentSource: 'request' },
    { id: 'delete', path: 'src/old.py', operation: 'delete', confirmed: true, status: 'done', deletions: 4 },
  ];
  const { root, inspections } = await mount(t, [{ id: 'files', status: 'running', fileChanges: files }]);
  assert.match(textOf(root), /已创建src\/new.py\+2−0/);
  assert.match(textOf(root), /已删除src\/old.py−4/);
  assert.doesNotMatch(textOf(root), /已修改/);
  assert.equal(byClass(root, 'oxc-worklog__line-count').length, 3);
  byClass(root, 'oxc-worklog__file-path')[0].props.onClick();
  assert.deepEqual(inspections, [{ kind: 'file', stepId: 'files', fileId: 'create', path: 'src/new.py' }]);
  assert.equal(byClass(root, 'oxc-worklog__file-detail').length, 0);
  byClass(root, 'oxc-worklog__file-toggle')[0].props.onClick();
  byClass(root, 'oxc-worklog__file-toggle')[1].props.onClick();
  await vue.nextTick();
  assert.equal(byClass(root, 'oxc-worklog__file-detail').length, 2);
  assert.match(textOf(root), /拟议变更/);
  assert.equal(byClass(root, 'oxc-worklog__diff').length, 3);
});

/** 文件差异保持惰性，长文本限制渲染但复制完整已收数据。 / Keep diffs inert and bound rendering while copying all received text. */
test('file diff rendering is inert bounded and exactly copyable', async (t) => {
  const copied = [];
  mockClipboard(t, async (text) => { copied.push(text); });
  const diff = ['+<script>evil()</script>', ...Array.from({ length: 550 }, (_, i) => `+line ${i}`)].join('\n');
  const { root } = await mount(t, [{ id: 'safe', status: 'done', fileChanges: [{ id: 'f', path: 'src/<img>.txt', operation: 'write', status: 'done', confirmed: true, diff, contentSource: 'receipt' }] }]);
  byClass(root, 'oxc-worklog__file-toggle')[0].props.onClick();
  await vue.nextTick();
  assert.equal(nodes(root, (node) => node.type === 'script' || node.type === 'img' || node.props.innerHTML !== undefined).length, 0);
  const detail = byClass(root, 'oxc-worklog__file-detail')[0];
  assert.equal(nodes(detail, (node) => node.type === 'span' && node.props.class === 'is-added').length, 500);
  assert.match(textOf(detail), /展示前 500 行/);
  await byClass(detail, 'oxc-worklog__copy-action')[0].props.onClick();
  await vue.nextTick();
  assert.deepEqual(copied, [diff]);
  assert.match(textOf(detail), /已复制/);
});
