#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Standalone WorldGen worker.

This file is intentionally light until `generate_worldgen_asset` is called so it
can be imported by the desktop runtime even when WorldGen/Torch are not present.
Run it with a Python environment where the ZiYang-xie/WorldGen package and its
GPU dependencies are installed.
"""

from __future__ import annotations

import argparse
import base64
import json
import os
import sys
import time
from pathlib import Path
from typing import Any, Dict


TRANSPARENT_PNG_BASE64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADElEQVR42mP8z8BQDwAFgwJ/l4t9NwAAAABJRU5ErkJggg=="
)


def _clean_text(value: Any, fallback: str = "") -> str:
    text = str(value or fallback).strip()
    return text if text else fallback


def _as_bool(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def _add_worldgen_repo_to_path(repo: str) -> None:
    root = Path(repo).expanduser().resolve() if repo else None
    if not root:
        return
    src = root / "src"
    for candidate in (str(src), str(root)):
        if candidate and candidate not in sys.path:
            sys.path.insert(0, candidate)


def _write_preview_png(path: Path) -> None:
    if not path.exists():
        path.write_bytes(base64.b64decode(TRANSPARENT_PNG_BASE64))


def generate_worldgen_asset(payload: Dict[str, Any]) -> Dict[str, Any]:
    started = time.time()
    output_dir = Path(_clean_text(payload.get("output_dir"), ".")).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    worldgen_repo = _clean_text(payload.get("worldgen_repo") or os.getenv("OPENXNET_WORLDGEN_REPO"))
    _add_worldgen_repo_to_path(worldgen_repo)

    prompt = _clean_text(payload.get("prompt"))
    if not prompt:
        raise ValueError("WorldGen prompt is empty")

    mode = _clean_text(payload.get("mode"), "t2s")
    return_mesh = _as_bool(payload.get("return_mesh"), True)
    use_sharp = _as_bool(payload.get("use_sharp"), False)
    # WorldGen's mesh mode does not benefit from background inpainting and its
    # demo explicitly keeps the two apart.
    inpaint_bg = _as_bool(payload.get("inpaint_bg"), False) and not return_mesh
    resolution = int(payload.get("resolution") or 1600)
    low_vram = payload.get("low_vram")
    if not isinstance(low_vram, bool):
        low_vram = None
    device_name = _clean_text(payload.get("device") or os.getenv("OPENXNET_WORLDGEN_DEVICE"), "cuda")
    lora_path = _clean_text(payload.get("lora_path") or os.getenv("OPENXNET_WORLDGEN_LORA_PATH"))

    import torch
    import open3d as o3d
    from worldgen import WorldGen

    device = torch.device(device_name if torch.cuda.is_available() or device_name == "cpu" else "cpu")
    kwargs = {
        "mode": mode,
        "use_sharp": use_sharp,
        "inpaint_bg": inpaint_bg,
        "resolution": resolution,
        "device": device,
        "low_vram": low_vram,
    }
    if lora_path:
        kwargs["lora_path"] = lora_path

    worldgen = WorldGen(**kwargs)
    mesh = worldgen.generate_world(prompt=prompt, return_mesh=True)

    mesh_path = output_dir / "scene.glb"
    ok = o3d.io.write_triangle_mesh(str(mesh_path), mesh)
    if not ok or not mesh_path.is_file():
        raise RuntimeError("open3d failed to write scene.glb")

    preview_path = output_dir / "preview.png"
    _write_preview_png(preview_path)

    return {
        "status": "ready",
        "backend": "worldgen-worker",
        "message": "WorldGen mesh generated by worker.",
        "mesh_path": str(mesh_path),
        "mesh_bytes": mesh_path.stat().st_size,
        "preview_path": str(preview_path),
        "preview_bytes": preview_path.stat().st_size,
        "elapsed_seconds": round(time.time() - started, 3),
        "runtime": {
            "worldgen_repo": worldgen_repo,
            "python": sys.executable,
            "device": str(device),
            "torch": getattr(torch, "__version__", ""),
            "cuda_available": bool(torch.cuda.is_available()),
            "low_vram": low_vram,
            "resolution": resolution,
            "mode": mode,
            "use_sharp": use_sharp,
            "inpaint_bg": inpaint_bg,
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="OpenXnet WorldGen worker")
    parser.add_argument("--input", required=True, help="Path to request JSON")
    parser.add_argument("--output", required=True, help="Path to result JSON")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)
    payload = json.loads(input_path.read_text(encoding="utf-8"))
    try:
        result = generate_worldgen_asset(payload)
    except Exception as exc:
        result = {
            "status": "failed",
            "backend": "worldgen-worker",
            "error": {
                "code": "WORLDGEN_WORKER_FAILED",
                "message": str(exc)[:2000],
            },
        }
        output_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
        print(json.dumps(result, ensure_ascii=False), flush=True)
        return 1

    output_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps(result, ensure_ascii=False), flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
