/*
 * Copyright (C) 2026 Synapxnet. All rights reserved.
 * This file is Synapxnet Proprietary and Confidential. It is strictly
 * forbidden to copy, distribute, or use without explicit authorization.
 * Skill 复用环境与制品回归 / Skill reuse environment and artifact regression.
 * Author: maoyo | Department: 研发部 | Date: 2026-09-14
 * Version: 1.0.0 | Security Level: INTERNAL
 * __version__: 1.0.0 | __author__: maoyo | __copyright__: Copyright 2026 Synapxnet
 * __maintainer__: maoyo | __email__: synapxnet@gmail.com
 */
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { appendFile, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { ApplicationSkillRuntimeService } from "../skills/application-skill-runtime";
import { readCompetitionSkillCertification, resolveCompetitionEnvironmentFingerprint, type CompetitionSkillCertificationInput } from "./competition-skill-certification";

const FINGERPRINT = "goai-staging@150.109.52.248:agentteams-v1.2.0";
const ENDPOINTS = { aiops: "https://aiops.contract.test/", dataops: "https://dataops.contract.test/", mlops: "https://mlops.contract.test/" } as const;

/** 使用实际 Skill Runtime 在临时目录生成制品，仅构造测试回执。 / Generate artifacts with the actual Skill Runtime in a temporary directory and construct a test-only receipt. */
async function createArtifact(directory: string): Promise<CompetitionSkillCertificationInput> {
  const skillsDirectory = path.join(directory, "skills");
  const runtime = new ApplicationSkillRuntimeService({ globalSkillsRoot: skillsDirectory, bundledSkillsRoot: path.join(directory, "bundled"), state: { getSnapshot: () => ({ schema: "openxnet.legacy-renderer-state.v1", settingsRevision: 0, conversationsRevision: 0, generatedAt: new Date().toISOString(), settings: {}, conversations: [] }) } });
  const skillId = "contract-test-recovery";
  await runtime.crystallizeSkill({ name: "Contract test recovery", skillId, workflow: "Read evidence, approve, execute, verify.", status: "verified", source: "rehearsal", sourceEventIds: ["inc_contract_source"], environmentScope: "staging", environmentFingerprint: FINGERPRINT, certifications: [{ scope: "staging", status: "verified", environmentFingerprint: FINGERPRINT, evidenceEventIds: ["inc_contract_source"] }], syncToProject: false });
  const markdown = await readFile(path.join(skillsDirectory, skillId, "SKILL.md"));
  const manifest = await readFile(path.join(skillsDirectory, skillId, "openxnet.skill.json"));
  const artifactDigest = createHash("sha256").update(markdown).update(Buffer.from([0])).update(manifest).digest("hex");
  const receiptPath = path.join(directory, "skill-certifications.json");
  await writeFile(receiptPath, JSON.stringify({ schema: "openxnet.skill-certification-receipt.v1", certifications: [{ skillId, sourceIncidentId: "inc_contract_source", lifecycleStatus: "verified", environmentScope: "staging", environmentFingerprint: FINGERPRINT, artifactDigest }] }));
  return { skillsDirectory, skillId, sourceIncidentId: "inc_contract_source", receiptPath };
}

/** 实际生成包可匹配外部认证，两份文件任何字节改变都会留下不匹配。 / Actual generated packages match external certification and any byte change remains a mismatch. */
for (const file of ["SKILL.md", "openxnet.skill.json"] as const) {
  /** 校验原始文件变化，禁止通过重新签发摘要掩盖变更。 / Detect raw-file changes without masking them through digest re-signing. */
  test(`Skill certification hashes actual generated bytes and detects edits to ${file}`, async () => {
    const directory = await mkdtemp(path.join(os.tmpdir(), "goai-skill-artifact-"));
    try {
      const input = await createArtifact(directory);
      const accepted = await readCompetitionSkillCertification(input);
      assert.ok(accepted);
      assert.equal(accepted.environmentFingerprint, FINGERPRINT);
      assert.equal(accepted.currentArtifactDigest, accepted.artifactDigest);
      await appendFile(path.join(input.skillsDirectory, input.skillId, file), "\n");
      const changed = await readCompetitionSkillCertification(input);
      assert.ok(changed);
      assert.equal(changed.artifactDigest, accepted.artifactDigest);
      assert.notEqual(changed.currentArtifactDigest, changed.artifactDigest);
    } finally {
      await rm(directory, { recursive: true, force: true });
    }
  });
}

/** 缺认证、错来源及错误制品路径不构造认证默认值。 / Missing receipts, wrong sources, and invalid paths never produce default certification values. */
test("Skill certification requires matching receipt source and manifest certification", async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "goai-skill-receipt-"));
  try {
    const input = await createArtifact(directory);
    assert.equal(await readCompetitionSkillCertification({ ...input, receiptPath: undefined }), null);
    assert.equal(await readCompetitionSkillCertification({ ...input, sourceIncidentId: "inc_another_source" }), null);
    assert.equal(await readCompetitionSkillCertification({ ...input, skillId: "../contract-test-recovery" }), null);
    const manifestPath = path.join(input.skillsDirectory, input.skillId, "openxnet.skill.json");
    const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as Record<string, unknown>;
    manifest.environment_fingerprint = "goai-staging@101.32.9.231:agentteams-v1.2.0";
    await writeFile(manifestPath, JSON.stringify(manifest));
    assert.equal(await readCompetitionSkillCertification(input), null);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

/** 同名同来源重复认证属于歧义，不能随意选一条放行。 / Duplicate certifications for the same Skill and source are ambiguous and cannot be selected arbitrarily. */
test("Skill certification rejects duplicate external bindings", async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), "goai-skill-duplicate-"));
  try {
    const input = await createArtifact(directory);
    const receipt = JSON.parse(await readFile(input.receiptPath!, "utf8")) as { certifications: unknown[] };
    receipt.certifications.push(receipt.certifications[0]);
    await writeFile(input.receiptPath!, JSON.stringify(receipt));
    assert.equal(await readCompetitionSkillCertification(input), null);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

/** 当前环境必须由三个实际配置入口和解析地址共同支持。 / All three actual configured endpoints and resolved addresses must support the current environment. */
test("current environment resolves only for matching HTTPS endpoints and server addresses", async () => {
  const input = { fingerprint: FINGERPRINT, expectedEndpoints: ENDPOINTS, resolveEndpoint: async (platform: keyof typeof ENDPOINTS) => ENDPOINTS[platform], resolveAddresses: async () => ["150.109.52.248"] };
  assert.equal(await resolveCompetitionEnvironmentFingerprint(input), FINGERPRINT);
  assert.equal(await resolveCompetitionEnvironmentFingerprint({ ...input, fingerprint: undefined }), null);
  assert.equal(await resolveCompetitionEnvironmentFingerprint({ ...input, resolveAddresses: async () => ["101.32.9.231"] }), null);
  assert.equal(await resolveCompetitionEnvironmentFingerprint({ ...input, resolveAddresses: async () => ["150.109.52.248", "101.32.9.231"] }), null);
  assert.equal(await resolveCompetitionEnvironmentFingerprint({ ...input, resolveEndpoint: async () => "https://other.contract.test/" }), null);
  assert.equal(await resolveCompetitionEnvironmentFingerprint({ ...input, resolveEndpoint: async () => "http://150.109.52.248/" }), null);
  assert.equal(await resolveCompetitionEnvironmentFingerprint({ ...input, resolveAddresses: async () => { throw new Error("contract test lookup failure"); } }), null);
});
