"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");

const { compile } = require("@vue/compiler-dom");
const { parse, parseFragment, serialize } = require("parse5");

const projectRoot = path.resolve(__dirname, "..");
const sourceHtmlPath = path.join(projectRoot, "static", "index.html");
const runtimeHtmlPath = path.join(projectRoot, "static", "index.precompiled.html");
const renderModulePath = path.join(projectRoot, "static", "js", "openxnet-render.js");
const renderModuleSource = "js/openxnet-render.js";

/**
 * Recursively find an HTML element with one exact id attribute.
 *
 * @param {object} node Current parse5 node.
 * @param {string} id Element identifier to locate.
 * @returns {object|null} Matching element node or null.
 */
function findElementById(node, id) {
  if (
    Array.isArray(node.attrs)
    && node.attrs.some((attribute) => attribute.name === "id" && attribute.value === id)
  ) {
    return node;
  }
  for (const child of node.childNodes || []) {
    const match = findElementById(child, id);
    if (match) {
      return match;
    }
  }
  return null;
}

/**
 * Recursively find a script element by its exact source attribute.
 *
 * @param {object} node Current parse5 node.
 * @param {string} source Script source to locate.
 * @returns {object|null} Matching script node or null.
 */
function findScriptBySource(node, source) {
  if (node.tagName === "script" && Array.isArray(node.attrs)) {
    const sourceAttribute = node.attrs.find((attribute) => attribute.name === "src");
    if (sourceAttribute?.value === source) {
      return node;
    }
  }
  for (const child of node.childNodes || []) {
    const match = findScriptBySource(child, source);
    if (match) {
      return match;
    }
  }
  return null;
}

/**
 * Indent generated compiler output without altering its semantics.
 *
 * @param {string} text Generated JavaScript.
 * @param {number} spaces Leading spaces per line.
 * @returns {string} Indented JavaScript.
 */
function indentText(text, spaces) {
  const prefix = " ".repeat(spaces);
  return text.split("\n").map((line) => `${prefix}${line}`).join("\n");
}

/**
 * Create a deterministic browser module containing the precompiled Vue render function.
 *
 * @param {string} template Browser-normalized application template.
 * @param {string} templateHash SHA-256 hash of the normalized template.
 * @returns {string} Complete generated JavaScript module.
 */
function buildRenderModule(template, templateHash) {
  const result = compile(template, {
    mode: "function",
    prefixIdentifiers: true,
    hoistStatic: true,
    cacheHandlers: true,
    onError(error) {
      throw error;
    },
  });
  return `"use strict";

// Generated by scripts/build_renderer_bootstrap.cjs from static/index.html.
// Template SHA-256: ${templateHash}
(function installOpenXnetRender(global, Vue) {
  if (!Vue) {
    throw new Error("Vue must load before the precompiled OpenXnet render function.");
  }
  const render = (function createOpenXnetRender(Vue) {
${indentText(result.code, 4)}
  }(Vue));
  Object.defineProperty(global, "openxnetCompiledRender", {
    configurable: false,
    enumerable: false,
    writable: false,
    value: render,
  });
}(window, window.Vue));
`;
}

/**
 * 清理生成文本中的行尾空白，并统一保留一个文件末尾换行。
 *
 * @param {string} content 待写入生成文件的 UTF-8 文本。
 * @returns {string} 已规范化行尾空白和末尾换行的文本。
 */
function normalizeGeneratedText(content) {
  const withoutTrailingWhitespace = content.replace(/[ \t]+(?=\r?$)/gmu, "");
  return `${withoutTrailingWhitespace.replace(/(?:\r?\n)*$/u, "")}\n`;
}

/**
 * Create one parse5 script node for the generated render module.
 *
 * @returns {object} Detached script element.
 */
function createRenderScriptNode() {
  const fragment = parseFragment(`<script src="${renderModuleSource}"></script>`);
  const script = fragment.childNodes?.[0];
  if (!script) {
    throw new Error("Failed to create the precompiled render script node.");
  }
  return script;
}

/**
 * Compile the source template and create both deterministic runtime artifacts.
 *
 * @returns {{runtimeHtml: string, renderModule: string, templateHash: string}} Generated artifacts.
 */
function buildArtifacts() {
  const sourceHtml = fs.readFileSync(sourceHtmlPath, "utf8");
  const document = parse(sourceHtml);
  const applicationRoot = findElementById(document, "app");
  if (!applicationRoot) {
    throw new Error("The source HTML does not contain the #app template root.");
  }
  const normalizedTemplate = serialize(applicationRoot);
  const templateHash = crypto.createHash("sha256").update(normalizedTemplate).digest("hex");
  const renderModule = normalizeGeneratedText(
    buildRenderModule(normalizedTemplate, templateHash),
  );

  applicationRoot.childNodes = [];
  applicationRoot.attrs.push({ name: "data-template-sha256", value: templateHash });
  const vueScript = findScriptBySource(document, "libs/vue.global.prod.js");
  const scriptParent = vueScript?.parentNode;
  if (!vueScript || !scriptParent || !Array.isArray(scriptParent.childNodes)) {
    throw new Error("The Vue runtime script could not be located in source HTML.");
  }
  const vueScriptIndex = scriptParent.childNodes.indexOf(vueScript);
  const renderScript = createRenderScriptNode();
  renderScript.parentNode = scriptParent;
  scriptParent.childNodes.splice(vueScriptIndex + 1, 0, renderScript);

  return {
    runtimeHtml: normalizeGeneratedText(serialize(document)),
    renderModule,
    templateHash,
  };
}

/**
 * Write a UTF-8 artifact only when its contents changed.
 *
 * @param {string} filePath Destination artifact path.
 * @param {string} content Generated UTF-8 content.
 */
function writeArtifact(filePath, content) {
  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
  if (current === content) {
    return;
  }
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
}

/**
 * Verify committed artifacts exactly match the source template.
 *
 * @param {{runtimeHtml: string, renderModule: string}} artifacts Expected artifacts.
 */
function checkArtifacts(artifacts) {
  const diagnostics = [];
  for (const [filePath, expected] of [
    [runtimeHtmlPath, artifacts.runtimeHtml],
    [renderModulePath, artifacts.renderModule],
  ]) {
    const actual = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
    if (actual !== expected) {
      diagnostics.push(`${path.relative(projectRoot, filePath)} is stale or missing.`);
    }
  }
  if (diagnostics.length > 0) {
    throw new Error(`${diagnostics.join("\n")}\nRun npm run build:renderer-bootstrap.`);
  }
}

/** Build or verify the precompiled Renderer bootstrap artifacts. */
function main() {
  const artifacts = buildArtifacts();
  if (process.argv.includes("--check")) {
    checkArtifacts(artifacts);
    process.stdout.write(`Renderer bootstrap artifacts are current (${artifacts.templateHash}).\n`);
    return;
  }
  writeArtifact(runtimeHtmlPath, artifacts.runtimeHtml);
  writeArtifact(renderModulePath, artifacts.renderModule);
  process.stdout.write(`Built precompiled Renderer bootstrap (${artifacts.templateHash}).\n`);
}

main();
